In [2]:
import torch
import torch.nn as nn
loss = nn.CrossEntropyLoss(reduction='none')
input = torch.randn(1, 2, requires_grad=True)
print("input",input)
target = torch.randn(1, 2)
print("target",target)
softmaxed = target.softmax(dim=1)
print("softmax",softmaxed)
output = loss(input, softmaxed)
print(output)
# output.backward()


input tensor([[-0.1613, -0.2479]], requires_grad=True)
target tensor([[-1.4096, -0.2902]])
softmax tensor([[0.2461, 0.7539]])
tensor([0.7161], grad_fn=<NegBackward0>)


In [4]:
# m = nn.LogSoftmax(dim=1)
loss = nn.NLLLoss(reduction='none')
# input is of size N x C = 3 x 5
input = torch.tensor([[0.80874, 0.585009, 0.479873, 0.350291, 0.895962],
    [0.82284, 0.746605, 0.174108, 0.858943, 0.710501],
    [0.513535, 0.303995, 0.0149846, 0.0914029, 0.364452]])

# take the log of the softmax to get the log probabilities
input = torch.log(input)
print(input.shape)
# each element in target has to have 0 <= value < C
target = torch.tensor([1,2,4])
output = loss(input, target)
print(output)
# output.backward()


torch.Size([3, 5])
tensor([0.5361, 1.7481, 1.0094])


In [ ]:
# Example of target with class indices
loss = nn.CrossEntropyLoss(reduction='none')
output = loss(input, target)
print(output)
# Example of target with class probabilities
target = target.softmax(dim=1)
output = loss(input, target)
print(output)

tensor([1.6689, 2.1257, 1.5191])


IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)