In [2]:
import torch
import torch.nn as nn
loss = nn.CrossEntropyLoss(reduction='none')
input = torch.randn(1, 2, requires_grad=True)
print("input",input)
target = torch.randn(1, 2)
print("target",target)
softmaxed = target.softmax(dim=1)
print("softmax",softmaxed)
output = loss(input, softmaxed)
print(output)
# output.backward()


input tensor([[-0.1613, -0.2479]], requires_grad=True)
target tensor([[-1.4096, -0.2902]])
softmax tensor([[0.2461, 0.7539]])
tensor([0.7161], grad_fn=<NegBackward0>)


In [4]:
# m = nn.LogSoftmax(dim=1)
loss = nn.NLLLoss(reduction='none')
# input is of size N x C = 3 x 5
input = torch.tensor([[0.80874, 0.585009, 0.479873, 0.350291, 0.895962],
    [0.82284, 0.746605, 0.174108, 0.858943, 0.710501],
    [0.513535, 0.303995, 0.0149846, 0.0914029, 0.364452]])

# take the log of the softmax to get the log probabilities
input = torch.log(input)
print(input.shape)
# each element in target has to have 0 <= value < C
target = torch.tensor([1,2,4])
output = loss(input, target)
print(output)
# output.backward()


torch.Size([3, 5])
tensor([0.5361, 1.7481, 1.0094])


In [13]:
# read arrays from .npy files and func Linear to compare
import numpy as np
import torch
import torch.nn as nn

inp = np.load('../with-torch-tests/cross-entropy-layer/h_inp.npy')
print(inp)
target = np.load('../with-torch-tests/cross-entropy-layer/h_targets.npy').astype(np.int64)
h_losses = np.load('../with-torch-tests/cross-entropy-layer/h_losses.npy')
h_softmax = np.load('../with-torch-tests/cross-entropy-layer/h_softmaxed.npy')
inp_torch = torch.from_numpy(inp).to(torch.float32)
inp_torch = torch.log(inp_torch)
target_torch = torch.from_numpy(target).to(torch.int64)

#apply softmax
m = nn.Softmax(dim=1)
inp_torch_1 = m(inp_torch)
print("soft torch inp",inp_torch_1)

#apply log softmax
m = nn.LogSoftmax(dim=1)
inp_torch_2 = m(inp_torch)
print("log torch inp",inp_torch_2)

#apply NLLLoss
loss = nn.NLLLoss(reduction='none')
losses = loss(inp_torch_2, target_torch)
print("torch losses", losses)

#compare
print("h_losses", h_losses)
print("H_sofqmax", h_softmax)

[[0.0011597  0.23557237 0.6481521 ]
 [0.07437361 0.2702414  0.36002687]
 [0.25528732 0.98529005 0.31891844]]
soft torch inp tensor([[0.0013, 0.2662, 0.7325],
        [0.1055, 0.3835, 0.5109],
        [0.1637, 0.6318, 0.2045]])
log torch inp tensor([[-6.6373, -1.3234, -0.3113],
        [-2.2486, -0.9584, -0.6715],
        [-1.8097, -0.4592, -1.5872]])
torch losses tensor([6.6373, 2.2486, 1.5872])
h_losses [1.428864  1.2661014 1.3572543]
H_sofqmax [[-1.428864   -1.1944513  -0.78187156]
 [-1.2661014  -1.0702336  -0.98044807]
 [-1.4208856  -0.69088274 -1.3572543 ]]
