In [2]:
import torch
import torch.nn as nn
loss = nn.CrossEntropyLoss(reduction='none')
input = torch.randn(1, 2, requires_grad=True)
print("input",input)
target = torch.randn(1, 2)
print("target",target)
softmaxed = target.softmax(dim=1)
print("softmax",softmaxed)
output = loss(input, softmaxed)
print(output)
# output.backward()


input tensor([[-0.1613, -0.2479]], requires_grad=True)
target tensor([[-1.4096, -0.2902]])
softmax tensor([[0.2461, 0.7539]])
tensor([0.7161], grad_fn=<NegBackward0>)


In [4]:
# m = nn.LogSoftmax(dim=1)
loss = nn.NLLLoss(reduction='none')
# input is of size N x C = 3 x 5
input = torch.tensor([[0.80874, 0.585009, 0.479873, 0.350291, 0.895962],
    [0.82284, 0.746605, 0.174108, 0.858943, 0.710501],
    [0.513535, 0.303995, 0.0149846, 0.0914029, 0.364452]])

# take the log of the softmax to get the log probabilities
input = torch.log(input)
print(input.shape)
# each element in target has to have 0 <= value < C
target = torch.tensor([1,2,4])
output = loss(input, target)
print(output)
# output.backward()


torch.Size([3, 5])
tensor([0.5361, 1.7481, 1.0094])


In [2]:
# read arrays from .npy files and func Linear to compare
import numpy as np
import torch
import torch.nn as nn

inp = np.load('../with-torch-tests/cross-entropy-layer/h_predictions.npy')
target = np.load('../with-torch-tests/cross-entropy-layer/h_targets.npy')
h_losses = np.load('../with-torch-tests/cross-entropy-layer/h_losses.npy')
inp_torch = torch.from_numpy(inp).to(torch.float32)
inp_torch = torch.log(inp_torch)
target_torch = torch.from_numpy(target).to(torch.int64)
loss = nn.NLLLoss(reduction='none')
out_torch = loss(inp_torch, target_torch)

print(h_losses[0:5])
print(out_torch[0:5])
print(np.allclose(h_losses, out_torch.detach().numpy(), atol=1e-4, rtol=1e-4))

[[7.3754084e-01 3.7342447e-01 9.5367289e-01 ... 5.4902799e-02
  8.1377608e-01 4.7416610e-01]
 [7.8127384e-02 8.2253486e-01 4.8448133e-01 ... 8.9083529e-01
  6.8590349e-01 5.9517199e-01]
 [8.7215799e-01 8.6217839e-01 4.2280343e-01 ... 8.0529189e-01
  1.6940825e-01 2.4695578e-01]
 ...
 [7.9311504e+00 8.1496626e-01 1.0159612e-01 ... 7.3689991e-01
  9.6874905e-01 9.7122103e-01]
 [7.9042939e-03 8.5082555e-01 7.0662558e-01 ... 4.6308786e-01
  7.9729605e-01 2.4710837e-01]
 [5.4576248e-01 1.8927580e-01 6.8874174e-01 ... 6.7033905e-01
  1.4654988e+00 9.1537219e-01]]
[2.9195728  1.2787329  0.11892429 0.10178272 0.86642134]
tensor([2.9196, 1.2787, 0.1189, 0.1018, 0.8664])
True
