In [14]:
# read arrays from .npy files and func Linear to compare
import numpy as np
import torch
import torch.nn as nn

inp = np.load('../with-torch-tests/softmax-layer/h_inp.npy')
out = np.load('../with-torch-tests/softmax-layer/h_out.npy')

#apply softmax with torch
inp_torch = torch.from_numpy(inp).to(torch.float32)
out_torch = nn.functional.softmax(inp_torch, dim=1)
 
print(*out)
print(*out_torch.detach().numpy())
print( np.allclose(out, out_torch.detach().numpy(), atol=1e-4, rtol=1e-4))

[0.         0.00157026 0.9984297 ] [0.40329954 0.59670043 0.        ] [2.1250953e-05 9.9997878e-01 0.0000000e+00]
[0.         0.00157026 0.9984297 ] [0.40329954 0.59670043 0.        ] [2.1250953e-05 9.9997878e-01 0.0000000e+00]
True


In [15]:
# read arrays from .npy files and func Linear to compare
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

inp = np.load('../with-torch-tests/softmax-layer/h_inp.npy')
target = np.load('../with-torch-tests/cross-entropy-layer/h_targets.npy')
out = np.load('../with-torch-tests/cross-entropy-layer/h_losses.npy')

#apply softmax with torch
inp_torch = torch.from_numpy(inp).to(torch.float32).requires_grad_(True)
target = torch.from_numpy(target).to(torch.int64)
print(target)
out_torch = F.cross_entropy(inp_torch,target,reduction='sum')
 
print(out)
print(out_torch)
print( np.allclose(out, out_torch.detach().numpy(), atol=1e-4, rtol=1e-4))

# backpropagation
out_torch.backward()
print(*inp_torch.grad.detach().numpy())

# read arrays from .npy files and func Linear to compare
grad = np.load('../with-torch-tests/cross-entropy-backward/h_dlogits_after.npy')
print(*grad)

tensor([2, 0, 1])
[1.5712201e-03 9.0807462e-01 2.0027361e-05]
tensor(0.9097, grad_fn=<NllLossBackward0>)
False
[ 0.          0.00157026 -0.00157028] [-0.59670043  0.59670043  0.        ] [ 2.1250959e-05 -2.1219254e-05  0.0000000e+00]
[ 0.          0.00157026 -0.00157028] [-0.59670043  0.59670043  0.        ] [ 2.1250953e-05 -2.1219254e-05  0.0000000e+00]
