In [ ]:

import torch
import torch.nn as nn
import torch.optim as optim

# Define a custom neural network class
class SimpleNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(SimpleNN, self).__init__()
        
        # Define the network layers
        self.linear1 = nn.Linear(input_size, hidden_size) # First linear layer
        self.activation1 = nn.ReLU() # Activation function after the first layer
        self.linear2 = nn.Linear(hidden_size, output_size) # Second linear layer
        self.softmax = nn.Softmax(dim=1) # Softmax layer for the output
        self.logsoftmax = nn.LogSoftmax(dim=1) # LogSoftmax layer for the output
    
    def forward(self, x):
        # Define the forward pass
        x = self.linear1(x)
        x = self.activation1(x)
        x = self.linear2(x)
        x = self.softmax(x)
        x = self.logsoftmax(x)
        return x

# Create an instance of the network
input_size = 10
hidden_size = 5
output_size = 3
model = SimpleNN(input_size, hidden_size, output_size)

# Create a loss function
criterion = nn.NLLLoss()

# Create an optimizer
# optimizer = optim.SGD(model.parameters(), lr=0.01)

# Define a batch of inputs and targets
batch_size = 4
input_data = torch.randn(batch_size, input_size) # Random input tensor with batch size
targets = torch.randint(0, output_size, (batch_size,)) # Random target tensor for each input in the batch

# Forward pass
outputs = model(input_data)

# Compute loss
loss = criterion(outputs, targets)

# Backward pass
# loss.backward()

# Update weights
# optimizer.step()

# Optionally, print output and loss
print(f"Outputs:\n{outputs}")
print(f"Loss: {loss.item()}")


In [ ]:
# random array and save it to a file .npy
# import numpy as np

# B = 1000
# N = 100
# M = 30
# X = np.random.rand(B, N).astype(np.float32)
# W = np.random.rand(M,N).astype(np.float32)
# bias = np.random.rand(M).astype(np.float32)
# np.save('../with-torch-tests/linear-layer/X.npy', X)
# np.save('../with-torch-tests/linear-layer/W.npy', W)
# np.save('../with-torch-tests/linear-layer/bias.npy', bias)

# l = nn.Linear(N,M)
# l.weight.data = torch.from_numpy(W)
# l.bias.data = torch.from_numpy(bias)
# X_torch = torch.from_numpy(X)
# Y = l(X_torch)
# np.save('../with-torch-tests/linear-layer/Y.npy', Y.detach().numpy())
# print(Y[0,0:5])


In [32]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

# Load the input data
ln1b = np.load('../with-torch-tests/all-model-cpu/ln1b.npy')
ln1w = np.load('../with-torch-tests/all-model-cpu/ln1w.npy')
ln2b = np.load('../with-torch-tests/all-model-cpu/ln2b.npy')
ln2w = np.load('../with-torch-tests/all-model-cpu/ln2w.npy')
target = np.load('../with-torch-tests/all-model-cpu/target.npy')
X_c = np.load('../with-torch-tests/all-model-cpu/X_c.npy')

# get sizes
B,N = X_c.shape
H1,N = ln1w.shape
l1 = nn.Linear(N,H1)
l1.weight.data = torch.from_numpy(ln1w).to(torch.float32)
l1.bias.data = torch.from_numpy(ln1b).to(torch.float32)


H2,_ = ln2w.shape
l2 = nn.Linear(H1,H2)
l2.weight.data = torch.from_numpy(ln2w).to(torch.float32)
l2.bias.data = torch.from_numpy(ln2b).to(torch.float32)

X = torch.from_numpy(X_c).to(torch.float32)
Y1 = l1(X)
y1_relu = F.relu(Y1)
Y2 = l2(y1_relu)
criterion = nn.CrossEntropyLoss(reduction='sum')
loss = criterion(Y2, torch.from_numpy(target).long())
loss

tensor(176.5740, grad_fn=<NllLossBackward0>)

In [34]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

# Load the input data
ln1b = np.load('../with-torch-tests/all-model/ln1b.npy')
ln1w = np.load('../with-torch-tests/all-model/ln1w.npy')
ln2b = np.load('../with-torch-tests/all-model/ln2b.npy')
ln2w = np.load('../with-torch-tests/all-model/ln2w.npy')
target = np.load('../with-torch-tests/all-model/target.npy')
X_c = np.load('../with-torch-tests/all-model/X_c.npy')

# get sizes
B,N = X_c.shape
H1,N = ln1w.shape
l1 = nn.Linear(N,H1)
l1.weight.data = torch.from_numpy(ln1w).to(torch.float32)
l1.bias.data = torch.from_numpy(ln1b).to(torch.float32)


H2,_ = ln2w.shape
l2 = nn.Linear(H1,H2)
l2.weight.data = torch.from_numpy(ln2w).to(torch.float32)
l2.bias.data = torch.from_numpy(ln2b).to(torch.float32)

X = torch.from_numpy(X_c).to(torch.float32)
Y1 = l1(X)
y1_relu = F.relu(Y1)
Y2 = l2(y1_relu)
criterion = nn.CrossEntropyLoss(reduction='sum')
loss = criterion(Y2, torch.from_numpy(target).long())
loss

tensor(176.5740, grad_fn=<NllLossBackward0>)

In [ ]:
# read arrays from .npy files and func Linear to compare
import numpy as np
import torch
import torch.nn as nn

X = np.load('../with-torch-tests/linear-layer/X_C.npy')
W = np.load('../with-torch-tests/linear-layer/W_C.npy')
bias = np.load('../with-torch-tests/linear-layer/bias_C.npy')
Y = np.load('../with-torch-tests/linear-layer/out_C.npy')
B,N = X.shape
_,M = Y.shape
l = nn.Linear(M,N)
l.weight.data = torch.from_numpy(W).to(torch.float32)
l.bias.data = torch.from_numpy(bias).to(torch.float32)
X_torch = torch.from_numpy(X).to(torch.float32)
Y_torch = l(X_torch)

print(Y[0,0:5])
print(Y_torch[0,0:5])
print( np.allclose(Y, Y_torch.detach().numpy(), atol=1e-4, rtol=1e-4))



In [ ]:
# Relu forward and backward tests
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

# Load data
X = np.load(r'../with-torch-tests/relu-layer/X_relu.npy')
Y = np.load(r'../with-torch-tests/relu-layer/out_relu.npy')
dY = np.load(r'../with-torch-tests/relu-layer/up_grad_relu.npy')
dX = np.load(r'../with-torch-tests/relu-layer/down_grad_relu.npy')
# Convert to PyTorch tensors
# make sure to set requires_grad=True for the input tensor so that the Autograd engine can compute the gradients
X_torch = torch.from_numpy(X).to(torch.float32).requires_grad_(True)
dY_torch = torch.from_numpy(dY).to(torch.float32)

# Forward pass with ReLU
relu = nn.ReLU()
Y_torch = relu(X_torch)

# Compare the forward pass results
print("Forward pass comparison:")
print("Y (numpy):", Y[0, 0:5])
print("Y_torch:", Y_torch.detach().numpy()[0, 0:5])
print("Match:", np.allclose(Y, Y_torch.detach().numpy(), atol=1e-4, rtol=1e-4))


# Validate the backward pass
Y_torch.backward(dY_torch)

# Get the gradients from X_torch
dX_torch = X_torch.grad

# Compare the backward pass results
print("\nBackward pass comparison:")
print("dX (numpy):", dX[0, 0:5])
print("dX_torch:", dX_torch.numpy()[0, 0:5])
print("Match:", np.allclose(dX, dX_torch.numpy(), atol=1e-4, rtol=1e-4))


In [ ]:
m = nn.LogSoftmax(dim=1)
loss = nn.NLLLoss()
# input is of size N x C = 3 x 5
input = torch.randn(3, 5, requires_grad=True)
# each element in target has to have 0 <= value < C
target = torch.tensor([1, 0, 4])
print(target.dtype)
output = loss(m(input), target)
output.backward()
# 2D loss example (used, for example, with image inputs)
N, C = 5, 4
loss = nn.NLLLoss()
# input is of size N x C x height x width
data = torch.randn(N, 16, 10, 10)
conv = nn.Conv2d(16, C, (3, 3))
m = nn.LogSoftmax(dim=1)
# each element in target has to have 0 <= value < C
target = torch.empty(N, 8, 8, dtype=torch.long).random_(0, C)
output = loss(m(conv(data)), target)
output.backward()

In [3]:
import numpy as np
A = np.load(r'../with-torch-tests/matmul/A.npy')
B = np.load(r'../with-torch-tests/matmul/B.npy')
C = np.load(r'../with-torch-tests/matmul/C.npy')
print(A.shape, B.shape, C.shape)
C_py = A @ B
print(C[:5,:5])
print(C_py[:5,:5])
print(np.allclose(C, C_py, atol=1e-4, rtol=1e-4))



(1048, 1048) (1048, 1048) (1048, 1048)
[[  8.910468   11.451632   10.183503    0.3938987  -5.9635134]
 [ -4.0297785 -14.136522    6.281192  -19.720121   23.324287 ]
 [ -1.1606363  -8.906321    7.2213197  -9.779897   -7.0447254]
 [ -4.011693  -17.447046  -12.836028   -3.1065748  -7.2245293]
 [-22.06999   -12.904112  -11.059555    6.7847285  20.716738 ]]
[[  8.910467    11.451638    10.1835       0.39389753  -5.9635115 ]
 [ -4.0297775  -14.136522     6.281187   -19.720123    23.324268  ]
 [ -1.1606376   -8.9063225    7.2213106   -9.779913    -7.044721  ]
 [ -4.01169    -17.447031   -12.836032    -3.1065707   -7.224536  ]
 [-22.07       -12.904118   -11.059553     6.784727    20.716742  ]]
True


In [1]:
# Test backward pass of the Linear layer
import numpy as np
import torch
import torch.nn as nn

# Load the input data
X = np.load('../with-torch-tests/linear-backward/X_c.npy')
W = np.load('../with-torch-tests/linear-backward/W_c.npy')
bias = np.load('../with-torch-tests/linear-backward/bias_c.npy')
upgrad = np.load('../with-torch-tests/linear-backward/up_grad.npy')


# out to comoare to
dLdb = np.load('../with-torch-tests/linear-backward/dLdb.npy')
dLdW = np.load('../with-torch-tests/linear-backward/dLdW.npy')
dLdX = np.load('../with-torch-tests/linear-backward/dLdX.npy')

# get sizes
B,N = X.shape
M,_ = W.shape

print(X.shape, W.shape, bias.shape, upgrad.shape)

lin = nn.Linear(N,M)
lin.weight.data = torch.from_numpy(W).to(torch.float32)
lin.bias.data = torch.from_numpy(bias).to(torch.float32)
# X must be a tensor with requires_grad=True
X_torch = torch.from_numpy(X).to(torch.float32).requires_grad_(True)
upgrad_torch = torch.from_numpy(upgrad).to(torch.float32)

# Forward pass
Y = lin(X_torch)

# Backward pass
Y.backward(upgrad_torch)

# Get the gradients
dLdW_torch = lin.weight.grad
dLdb_torch = lin.bias.grad
dLdX_torch = X_torch.grad

# Compare the gradients
print("dLdW (numpy):", dLdW[0, 0:5])
print("dLdW_torch:", dLdW_torch.numpy()[0, 0:5])
print("Match:", np.allclose(dLdW, dLdW_torch.numpy(), atol=1e-4, rtol=1e-4))

print("dLdb (numpy):", dLdb[0:10].reshape(-1, 1))
print("dLdb_torch:", dLdb_torch.numpy()[0:10].reshape(-1, 1))
print("Match:", np.allclose(dLdb.reshape(-1, 1), dLdb_torch.numpy().reshape(-1, 1), atol=1e-2, rtol=1e-2))

print("dLdX (numpy):", dLdX[0, 0:5])
print("dLdX_torch:", dLdX_torch.numpy()[0, 0:5])
print("Match:", np.allclose(dLdX, dLdX_torch.numpy(), atol=1e-4, rtol=1e-4))

(300, 1000) (350, 1000) (350,) (300, 350)
dLdW (numpy): [ 0.24916653 -8.158649    0.0767038   1.0023702  -2.7791066 ]
dLdW_torch: [ 0.24916653 -8.158649    0.0767038   1.0023702  -2.7791066 ]
Match: True
dLdb (numpy): [[20.059994 ]
 [15.267552 ]
 [11.244912 ]
 [13.10672  ]
 [18.342787 ]
 [-6.4514303]
 [-2.9472344]
 [ 5.5811644]
 [ 1.6450696]
 [-9.8003435]]
dLdb_torch: [[20.060001 ]
 [15.267556 ]
 [11.24491  ]
 [13.106721 ]
 [18.342783 ]
 [-6.4514284]
 [-2.947233 ]
 [ 5.5811644]
 [ 1.6450698]
 [-9.800346 ]]
Match: True
dLdX (numpy): [-5.308016   7.6920857  3.833842   2.9945598 -2.629773 ]
dLdX_torch: [-5.308016   7.6920857  3.833842   2.9945598 -2.629773 ]
Match: True
